[workspace]
members = [
    "snark-verifier",
    "snark-verifier-sdk",
]

[profile.dev]
opt-level = 3

# Local "release" mode, more optimized than dev but faster to compile than release
[profile.local]
inherits = "dev"
opt-level = 3
# Set this to 1 or 2 to get more useful backtraces
debug = true
debug-assertions = false
panic = 'unwind'
# better recompile times
incremental = true
lto = "thin"
codegen-units = 16

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
lto = "fat" 
# codegen-units = 1
panic = "abort"
incremental = false

# For performance profiling
[profile.flamegraph]
inherits = "release"
debug = true

[patch."ssh://github.com/axiom-crypto/axiom-core-working.git"]
halo2-base = { path = "../axiom-core-working/halo2-lib/halo2-base" }
halo2-ecc = { path = "../axiom-core-working/halo2-lib/halo2-ecc" }

[patch."https://github.com/axiom-crypto/halo2.git"]
halo2_proofs = { path = "../halo2/halo2_proofs" }
halo2curves = { path = "../halo2/arithmetic/curves" }
poseidon = { path = "../halo2/primitives/poseidon" }

# patch for now because PSE/halo2 has not yet updated halo2curves version, unnecessary if halo2_proofs is using latest halo2curves with Fq12 public
[patch."https://github.com/privacy-scaling-explorations/halo2curves.git"]
halo2curves = { path = "../halo2/arithmetic/curves" } 

# patch just because we cannot patch the same repo with different tag: serialization is already in latest PSE/halo2 but not in v2022_10_22
[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { git = "https://github.com/axiom-crypto/halo2.git", branch = "axiom/add-serialization" }