[package]
name = "plonk_verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.3"
lazy_static = "1.4.0"
num-bigint = "0.4"
num-traits = "0.2"
rand = "0.8"
rand_chacha = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
halo2_curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves", tag = "0.2.1", package = "halo2curves" }
ark-std = { version = "0.3", features = ["print-trace"] }
hex = "0.4.3"

# system_halo2
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2022_09_10", optional = true }

# loader_evm
ethereum_types = { package = "ethereum-types", version = "0.13.1", default-features = false, features = ["std"], optional = true }
sha3 = { version = "0.10.1", optional = true }
foundry_evm = { git = "https://github.com/jonathanpwang/foundry", package = "foundry-evm", branch = "fix/pin-revm-to-rev", optional = true }

# loader_halo2
halo2_ecc = { git = "https://github.com/jonathanpwang/halo2-ecc", tag = "v2022_09_29", default-features = false, optional = true }
poseidon = { git = "https://github.com/privacy-scaling-explorations/poseidon", branch = "padding", optional = true }

[dev-dependencies]
paste = "1.0.7"

# loader_evm
crossterm = { version = "0.22.1" }
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }

# zkevm
zkevm_circuit_benchmarks = {git = "https://github.com/privacy-scaling-explorations/zkevm-circuits.git", package = "circuit-benchmarks", features = ["benches"] }
zkevm_circuits = {git = "https://github.com/privacy-scaling-explorations/zkevm-circuits.git", package = "zkevm-circuits" }

[features]
default = ["loader_evm", "loader_halo2", "system_halo2"]
loader_evm = ["dep:ethereum_types", "dep:sha3", "dep:foundry_evm"]
loader_halo2 = ["dep:halo2_proofs", "dep:halo2_ecc", "dep:poseidon"]

system_halo2 = ["dep:halo2_proofs"]

sanity_check = []

[patch."https://github.com/privacy-scaling-explorations/halo2"]
# halo2_proofs = { path = "../halo2/halo2_proofs" }
halo2_proofs = { git = "https://github.com/axiom-crypto/halo2.git", branch = "serialize", package = "halo2_proofs" }

[[example]]
name = "evm-verifier"
required-features = ["loader_evm", "system_halo2"]

[[example]]
name = "evm-verifier-with-accumulator"
required-features = ["loader_halo2", "loader_evm", "system_halo2"]
