[package]
name = "plonk_verifier"
version = "0.1.0"
edition = "2021"

[patch."https://github.com/privacy-scaling-explorations/halo2curves"]
halo2curves = { git = "https://github.com/axiom-crypto/halo2.git", branch = "axiom/faster-witness-generation" }

# [patch."ssh://github.com/axiom-crypto/halo2-lib-working.git"]
# halo2_base = { path = "../halo2-lib-working/halo2_base" }
# halo2_ecc = { path = "../halo2-lib-working/halo2_ecc" }

[dependencies]
itertools = "0.10.3"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
num-integer = "0.1.45"
num-traits = "0.2.15"
rand = "0.8"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"

halo2_curves = { git = "https://github.com/axiom-crypto/halo2", branch = "axiom/faster-witness-generation", package = "halo2curves" }

# parallel
rayon = { version = "1.5.3", optional = true }

# system_halo2
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2022_10_22", optional = true }

# loader_evm
ethereum_types = { package = "ethereum-types", version = "0.14", default-features = false, features = ["std"], optional = true }
sha3 = { version = "0.10", optional = true }
revm = { version = "2.3.1", optional = true }
bytes = { version = "1.2", optional = true }
rlp = { version = "0.5", default-features = false, features = ["std"], optional = true }

# loader_halo2
halo2_base = { git = "ssh://github.com/axiom-crypto/halo2-lib-working.git", branch = "faster-and-compatible", package = "halo2_base", default-features = false, optional = true }
halo2_ecc = { git = "ssh://github.com/axiom-crypto/halo2-lib-working.git", branch = "faster-and-compatible", package = "halo2_ecc", default-features = false, optional = true }
halo2_wrong_ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2022_10_22", package = "ecc", optional = true }
poseidon = { git = "https://github.com/privacy-scaling-explorations/poseidon", tag = "v2022_10_22", optional = true }

[dev-dependencies]
ark-std = { version = "0.3.0", features = ["print-trace"] }
rand_chacha = "0.3.1"
paste = "1.0.7"

# system_halo2
halo2_ecc = { git = "ssh://github.com/axiom-crypto/halo2-lib-working.git", branch = "faster-and-compatible", package = "halo2_ecc" }
halo2_wrong_ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2022_10_22", package = "ecc" }

# loader_evm
crossterm = { version = "0.25" }
tui = { version = "0.19", default-features = false, features = ["crossterm"] }

[features]
default = ["loader_evm", "loader_halo2", "system_halo2"]

parallel = ["dep:rayon"]

loader_evm = ["dep:ethereum_types", "dep:sha3", "dep:revm", "dep:bytes", "dep:rlp"]
loader_halo2 = ["dep:halo2_proofs", "dep:halo2_base", "halo2_ecc", "dep:halo2_wrong_ecc", "dep:poseidon"]

system_halo2 = ["dep:halo2_proofs"]

[[example]]
name = "evm-verifier"
required-features = ["loader_evm", "system_halo2"]

[[example]]
name = "evm-verifier-with-accumulator"
required-features = ["loader_halo2", "loader_evm", "system_halo2"]

[[example]]
name = "recursion"
required-features = ["loader_halo2", "system_halo2"]

[profile.dev]
opt-level = 3

# Local "release" mode, more optimized than dev but much faster to compile than release
[profile.local]
inherits = "dev"
opt-level = 3
# Set this to 1 or 2 to get more useful backtraces
debug = 0
panic = 'unwind'
# better recompile times
incremental = true
codegen-units = 16

[profile.release]
debug = 0
opt-level = 3
lto = "fat" 
# codegen-units = 1
panic = "abort"
