name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: false

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install solc-select and solc
        run: |
          pip3 install solc-select
          solc-select use 0.8.19 --always-install

      - name: Run test
        run: cargo test --all --features "revm" -- --nocapture

      - name: Run example
        working-directory: "snark-verifier-sdk"
        run: cargo run --example standard_plonk --features "revm"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: false
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run clippy
        run: cargo clippy --all --all-targets -- -D warnings

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Run cargo audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
